apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: tekton-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: git@github.com:peters95/tekton.git
